### ISSUE TITLE
logoURIs for few Tokens are exmpty

### ISSUE THREAD

**Issue by skiran017** [tonic-foundation/token-list#1]
## Problem

I am using ```@tonic-foundation/token-list ``` package to get the list of tokens and their metaData on Near Mainnet. There are total of 59  tokens i can fetch as of now out of which 8 tokens have their logoURIs missing. The list is as follows :-

1. 1INCH 
2. GTC 
3. GRT 
4. HT 
5. MRCH
6. USN 
7. WETH 
8. wNEAR 
![image](https://user-images.githubusercontent.com/23178403/173167007-e7a52351-145d-4aed-9634-0cb398628027.png)

Can someone help in fixing these?

I do have the assets and can contribute either via raising the PR or to share the icon urls. Let me know.

Thank you.

**Comment by renthog** [comment]
Thanks for pointing this out. This is fixed in 0.0.5 https://github.com/tonic-foundation/token-list/releases/tag/v0.0.5

**Comment by skiran017** [comment]
thank you for the quick fix
