### ISSUE TITLE
update logoURL to latest 

### ISSUE THREAD

**Issue by skiran017** [tonic-foundation/token-list#5]
### Problem
Hello Team,
It was observed that few organizations have updated their brand logo as well as their token logos namely MetaPool.

It would be really helpful if someone can update their respective logos with the latest one. Assets can be found in the link below for tokens: META and stNEAR
https://drive.google.com/drive/u/0/folders/1tp1Dgr1jJOqZVgyiWi4K34poklwX9E74

For reference:
current logos:-
META 
![image](https://user-images.githubusercontent.com/23178403/178135573-f96a2d81-a68c-443e-b2c1-e36cc4c58672.png)

stNEAR
![image](https://user-images.githubusercontent.com/23178403/178135584-1c0b6f70-0738-4600-bd99-39b983b0c5fb.png)

Update Logos to be:-
META
![image](https://user-images.githubusercontent.com/23178403/178135656-a435ff8d-29e7-468d-aee3-4bb3ad34e822.png)

stNEAR
![image](https://user-images.githubusercontent.com/23178403/178135645-48b207ec-eaa0-4e4c-881e-d1fa2f7bf19e.png)

Thank you

**Comment by renthog** [comment]
Updated in 0.0.7, thanks.

**Comment by skiran017** [comment]
Thank you for quick update.
